name: Test
on: [push]
jobs:
  Assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Package project
        run: mvn -U clean package
